
# Adam PC
#FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04 

# 5TONIC server
FROM nvidia/cuda:12.0.0-runtime-ubuntu22.04

LABEL maintainer="azahir@pa.uc3m.es"

# Set bash as default shell, and avoid prompts during package installation
SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

# Install Python, pip, and essential tools
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-opencv \
    git \
    wget \
    && apt-get clean

# Install dependencies 
RUN pip3 install --no-cache-dir \
      keras==2.15.0 \
      tensorflow[and-cuda]~=2.15.0 \
      numpy \
      huggingface_hub \
      flask 

# Create a working directory
WORKDIR /app
